// Curated opening repertoire: ~27 families covering the main replies to 1.e4, 1.d4 and
// flank openings, each with several named variations. Every variation is a flat SAN move
// list (not a shared tree) — simpler to author and to step through on the board, at the
// cost of some repeated trunk moves across variations of the same family.
//
// Each move entry is { s: SAN, c: comment }. Comments explain the idea, not just the
// notation — that's the whole point of this screen. All lines are validated against
// chess.js in tools/validate-openings.js before shipping (a typo here would mean an
// illegal move the board can't play).

const OPENINGS = [
  // ---------------------------------------------------------------- 1.e4 e5 openings
  {
    id: 'italian',
    forColor: 'w',
    family: 'Italienne',
    eco: 'C50–C54',
    intro: 'Développement rapide et naturel visant f7, la case la plus fragile du camp noir. Idéale pour apprendre les bases du jeu ouvert.',
    variations: [
      {
        name: 'Giuoco Pianissimo',
        moves: [
          { s: 'e4', c: 'Contrôle le centre, ouvre la diagonale du fou et de la dame.' },
          { s: 'e5', c: 'Réponse symétrique, lutte pour le centre.' },
          { s: 'Nf3', c: 'Attaque e5 et développe.' },
          { s: 'Nc6', c: 'Défend e5, développe.' },
          { s: 'Bc4', c: "Vise f7 ; c'est l'idée de toute l'ouverture." },
          { s: 'Bc5', c: 'Développement miroir, même idée pour les Noirs.' },
          { s: 'c3', c: 'Prépare d4 pour prendre le centre en force.' },
          { s: 'Nf6', c: 'Attaque e4, développe.' },
          { s: 'd3', c: "Version prudente (\"pianissimo\") : soutient e4 sans se précipiter." },
          { s: 'd6', c: 'Solidifie e5, ouvre le fou c8.' },
          { s: 'O-O', c: 'Roi en sécurité.' },
          { s: 'O-O', c: 'Symétrie complète, partie stratégique et calme.' },
          { s: 'Re1', c: 'Renforce e4 en prévision de d4.' },
          { s: 'a6', c: 'Prophylaxie classique : empêche Bb5 ou Nb5 avant de continuer.' },
          { s: 'Bb3', c: 'Retraite préventive, garde le fou hors de prise.' },
          { s: 'h6', c: "Empêche Ng5 ou Bg5 : coup prophylactique typique de cette structure calme." },
        ],
      },
      {
        name: 'Évans Gambit',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nc6', c: '' },
          { s: 'Bc4', c: '' },
          { s: 'Bc5', c: '' },
          { s: 'b4', c: "Le gambit : sacrifie un pion pour gagner deux tempos sur le fou et prendre le centre." },
          { s: 'Bxb4', c: 'Accepte le pion.' },
          { s: 'c3', c: 'Chasse le fou et prépare d4.' },
          { s: 'Ba5', c: 'Garde la pression sur c3/d2, ligne principale.' },
          { s: 'd4', c: 'Grand centre de pions, avance de développement.' },
          { s: 'exd4', c: '' },
          { s: 'O-O', c: "Les Noirs sont en retard de développement, les Blancs ont l'initiative en échange du pion." },
          { s: 'd6', c: "Ligne solide : refuse d'accepter davantage de matériel (\"Defense normale\") plutôt que 7...dxc3." },
          { s: 'cxd4', c: 'Reconstitue le grand centre de pions.' },
          { s: 'Bb6', c: 'Range le fou en sécurité, hors de la colonne c.' },
          { s: 'Nc3', c: 'Développe en direction du roque long ou de d5.' },
          { s: 'Na5', c: "Manœuvre thématique : chasse le fou b3 avant qu'il ne devienne trop fort." },
          { s: 'Bd3', c: 'Retraite prudente, garde toutes les options.' },
        ],
      },
      {
        name: 'Défense des Deux Cavaliers',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nc6', c: '' },
          { s: 'Bc4', c: '' },
          { s: 'Nf6', c: 'Contre-attaque e4 au lieu de développer le fou — plus tranchant que Bc5.' },
          { s: 'Ng5', c: "Attaque f7 directement, profitant du retard de développement noir." },
          { s: 'd5', c: 'Seule réponse sérieuse : contre-attaque au centre.' },
          { s: 'exd5', c: '' },
          { s: 'Na5', c: 'Ligne moderne : chasse le fou plutôt que de sacrifier en Nxd5.' },
          { s: 'Bb5+', c: 'Échec intermédiaire important.' },
          { s: 'c6', c: '' },
          { s: 'dxc6', c: '' },
          { s: 'bxc6', c: 'Position déséquilibrée et riche, typique de la ligne.' },
          { s: 'Be2', c: "Retraite prudente, laisse les Noirs prouver leur compensation." },
          { s: 'h6', c: "Chasse le cavalier avant de continuer le développement." },
          { s: 'Nf3', c: 'Recule vers une case sûre.' },
          { s: 'e4', c: "Gagne un tempo supplémentaire sur le cavalier tout en prenant de l'espace." },
          { s: 'Nd4', c: 'Centralise activement plutôt que de reculer davantage, position dynamique et déséquilibrée.' },
        ],
      },
    ],
  },

  {
    id: 'ruy-lopez',
    forColor: 'w',
    family: 'Espagnole (Ruy Lopez)',
    eco: 'C60–C99',
    intro: "L'ouverture la plus jouée au sommet depuis 400 ans. Le fou b5 fait pression sur le cavalier qui défend e5, préparant un jeu positionnel riche.",
    variations: [
      {
        name: 'Défense Berlinoise',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nc6', c: '' },
          { s: 'Bb5', c: "Attaque le cavalier qui défend e5 : si les Noirs ne réagissent pas, Bxc6 puis Nxe5 gagne un pion." },
          { s: 'Nf6', c: 'La défense berlinoise : contre-attaque au lieu de défendre e5.' },
          { s: 'O-O', c: '' },
          { s: 'Nxe4', c: 'Prend le pion, comptant sur des complications favorables.' },
          { s: 'd4', c: 'Ouvre le centre pour exploiter le retard de développement noir.' },
          { s: 'Nd6', c: 'Recule pour garder le matériel.' },
          { s: 'Bxc6', c: '' },
          { s: 'dxc6', c: '' },
          { s: 'dxe5', c: '' },
          { s: 'Nf5', c: '' },
          { s: 'Qxd8+', c: "Mène au fameux \"endgame berlinois\", réputé imprenable et popularisé par Kramnik contre Kasparov en 2000." },
          { s: 'Kxd8', c: '' },
          { s: 'Nc3', c: 'Développe en direction du roque long, plan classique dans cette structure.' },
          { s: 'Ke8', c: "Recentralise le roi en sécurité plutôt que de rester sur d8." },
          { s: 'h3', c: "Empêche ...Bg4, prophylaxie typique avant de continuer le développement." },
        ],
      },
      {
        name: 'Défense Fermée (Morphy)',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nc6', c: '' },
          { s: 'Bb5', c: '' },
          { s: 'a6', c: "Pose la question au fou : la défense Morphy, la réponse la plus populaire." },
          { s: 'Ba4', c: 'Garde la pression sur c6 plutôt que de prendre.' },
          { s: 'Nf6', c: 'Contre-attaque e4.' },
          { s: 'O-O', c: '' },
          { s: 'Be7', c: 'Développement solide et classique.' },
          { s: 'Re1', c: 'Soutient e4 en prévision de ...b5.' },
          { s: 'b5', c: 'Gagne de l\'espace et chasse le fou avant de développer.' },
          { s: 'Bb3', c: '' },
          { s: 'd6', c: '' },
          { s: 'c3', c: "Prépare d4 pour prendre un grand centre : la tabiya principale de l'Espagnole fermée." },
          { s: 'O-O', c: '' },
          { s: 'h3', c: "Empêche ...Bg4 avant toute chose : le coup prophylactique le plus emblématique de l'Espagnole." },
          { s: 'Na5', c: 'Chasse le fou b3, manœuvre thématique du système Chigorine.' },
          { s: 'Bc2', c: 'Retraite, garde la diagonale pour plus tard.' },
          { s: 'c5', c: "Gagne de l'espace à l'aile dame, préparant ...Nc6 ou ...Qc7 selon les plans." },
        ],
      },
      {
        name: 'Variante d\'Échange',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nc6', c: '' },
          { s: 'Bb5', c: '' },
          { s: 'a6', c: '' },
          { s: 'Bxc6', c: "Échange tout de suite contre le double pion noir, en échange d'un léger avantage de structure à long terme." },
          { s: 'dxc6', c: 'Les Noirs récupèrent la paire de fous mais acceptent des pions doublés.' },
          { s: 'O-O', c: '' },
          { s: 'f6', c: 'Solidifie e5 avant de développer, plan typique de cette structure.' },
          { s: 'd4', c: '' },
          { s: 'exd4', c: '' },
          { s: 'Nxd4', c: '' },
          { s: 'c5', c: 'Chasse le cavalier, gagne du terrain sur l\'aile dame.' },
          { s: 'Nb3', c: "Fin de partie légèrement meilleure pour les Blancs, arme favorite de Fischer et Kasparov." },
          { s: 'Qxd1', c: 'Simplifie directement vers le type de finale recherché par les Blancs.' },
          { s: 'Rxd1', c: '' },
          { s: 'Bg4', c: 'Cloue le cavalier avant de continuer le développement.' },
          { s: 'f3', c: "Casse le clouage, quitte à affaiblir légèrement e3/g3, position typique de finale Lopez d'Échange." },
        ],
      },
    ],
  },

  {
    id: 'scotch',
    forColor: 'w',
    family: 'Écossaise',
    eco: 'C44–C45',
    intro: "Ouvre le centre dès le troisième coup plutôt que de développer un fou : position plus ouverte et concrète que l'Italienne ou l'Espagnole, très prisée par Kasparov dans les années 90.",
    variations: [
      {
        name: 'Ligne Principale (4...Cf6)',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nc6', c: '' },
          { s: 'd4', c: "Ouvre le centre immédiatement : l'idée signature de l'Écossaise." },
          { s: 'exd4', c: '' },
          { s: 'Nxd4', c: '' },
          { s: 'Nf6', c: 'Attaque e4 pendant que les Blancs viennent de bouger deux fois le même cavalier.' },
          { s: 'Nxc6', c: 'Échange immédiat plutôt que de défendre e4.' },
          { s: 'bxc6', c: '' },
          { s: 'e5', c: 'Gagne un tempo sur le cavalier tout en prenant de l\'espace.' },
          { s: 'Qe7', c: 'Contre-attaque e5 tout en préparant de reprendre le pion si besoin.' },
          { s: 'Qe2', c: 'Défend e5 en évitant l\'échange de dames à ce stade.' },
          { s: 'Nd5', c: 'Centralise le cavalier, position typique de la Ligne Principale.' },
          { s: 'c4', c: 'Chasse le cavalier tout en gagnant de l\'espace.' },
          { s: 'Nb6', c: '' },
          { s: 'Nc3', c: 'Position équilibrée et riche, longtemps l\'arme principale de Kasparov contre 1...e5.' },
        ],
      },
      {
        name: 'Gambit Écossais',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nc6', c: '' },
          { s: 'd4', c: '' },
          { s: 'exd4', c: '' },
          { s: 'Bc4', c: "Retarde la reprise du pion pour développer avec tempo, dans l'esprit de l'Italienne." },
          { s: 'Nf6', c: 'Contre-attaque e4 plutôt que de défendre le pion d4 supplémentaire.' },
          { s: 'e5', c: 'Gagne un tempo en chassant le cavalier.' },
          { s: 'd5', c: 'Contre-attaque immédiatement le fou et le pion e5.' },
          { s: 'Bb5', c: 'Seule retraite qui garde la pression, clouant indirectement le cavalier c6.' },
          { s: 'Ne4', c: 'Centralise activement plutôt que de reculer.' },
          { s: 'Nxd4', c: 'Reprend enfin le pion, position tranchante et riche en tactique.' },
          { s: 'Bd7', c: 'Développement naturel tout en préparant de résoudre le clouage.' },
        ],
      },
    ],
  },

  {
    id: 'sicilian',
    forColor: 'b',
    family: 'Sicilienne',
    eco: 'B20–B99',
    intro: "La défense la plus jouée contre 1.e4 au haut niveau : asymétrique dès le premier coup, elle donne aux Noirs de vraies chances de gagner, au prix d'un jeu plus risqué.",
    variations: [
      {
        name: 'Najdorf',
        moves: [
          { s: 'e4', c: '' },
          { s: 'c5', c: 'Contre-attaque asymétrique sur l\'aile dame au lieu de disputer le centre directement.' },
          { s: 'Nf3', c: '' },
          { s: 'd6', c: 'Prépare Nf6 sans craindre e5.' },
          { s: 'd4', c: 'Ouvre le centre : idée thématique de presque toute Sicilienne.' },
          { s: 'cxd4', c: '' },
          { s: 'Nxd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'a6', c: "Le coup signature de la Najdorf : empêche Nb5/Bb5+ et prépare ...e5 ou ...b5." },
          { s: 'Be2', c: 'Système anglais, solide et flexible.' },
          { s: 'e5', c: 'Gagne de l\'espace au centre, thème classique de la Najdorf.' },
          { s: 'Nb3', c: 'Recule pour éviter d\'être chassé.' },
          { s: 'Be7', c: '' },
          { s: 'O-O', c: '' },
          { s: 'O-O', c: 'Position équilibrée et extrêmement riche en plans des deux côtés.' },
          { s: 'Be3', c: 'Développement naturel, prépare Qd2 et parfois le grand roque.' },
          { s: 'Be6', c: 'Développement symétrique, prépare ...Nbd7 et ...Rc8.' },
          { s: 'Qd2', c: 'Coordonne les pièces avant de choisir un plan à l\'aile roi ou dame.' },
          { s: 'Nbd7', c: 'Complète le développement, position typique de la Najdorf classique.' },
        ],
      },
      {
        name: 'Dragon',
        moves: [
          { s: 'e4', c: '' },
          { s: 'c5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'd6', c: '' },
          { s: 'd4', c: '' },
          { s: 'cxd4', c: '' },
          { s: 'Nxd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'g6', c: "Fianchetto du fou en g7 : la Dragon, nommée pour la ressemblance de la structure de pions avec une constellation." },
          { s: 'Be3', c: '' },
          { s: 'Bg7', c: '' },
          { s: 'f3', c: "Prépare Qd2 et O-O-O : l'Attaque Yougoslave, roque opposé et course à l'attaque des rois." },
          { s: 'O-O', c: '' },
          { s: 'Qd2', c: '' },
          { s: 'Nc6', c: 'Position extrêmement tranchante : chaque camp attaque le roque adverse.' },
        ],
      },
      {
        name: 'Scheveningen',
        moves: [
          { s: 'e4', c: '' },
          { s: 'c5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'd6', c: '' },
          { s: 'd4', c: '' },
          { s: 'cxd4', c: '' },
          { s: 'Nxd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'e6', c: "Structure ...d6+...e6, souple et solide, laissant le fou f8 sortir en e7 ou b4." },
          { s: 'Be2', c: '' },
          { s: 'a6', c: '' },
          { s: 'O-O', c: '' },
          { s: 'Be7', c: '' },
          { s: 'f4', c: "Gagne de l'espace, prépare une attaque à la Keres (g4-g5) si les Noirs tardent à roquer." },
          { s: 'O-O', c: 'Position flexible, souvent transpose vers la Najdorf ou le Schéma classique.' },
        ],
      },
      {
        name: 'Anti-Sicilienne : Variante Alapin (2.c3)',
        moves: [
          { s: 'e4', c: '' },
          { s: 'c5', c: '' },
          { s: 'c3', c: "Évite la théorie lourde des lignes principales : prépare d4 pour obtenir un centre classique." },
          { s: 'd5', c: 'Frappe immédiatement le centre, réponse la plus directe.' },
          { s: 'exd5', c: '' },
          { s: 'Qxd5', c: '' },
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Bg4', c: 'Développement actif, met en cause le cavalier f3.' },
          { s: 'Be2', c: '' },
          { s: 'e6', c: '' },
          { s: 'O-O', c: '' },
          { s: 'Nc6', c: 'Position quasi symétrique, plus calme que les lignes ouvertes.' },
        ],
      },
    ],
  },

  {
    id: 'french',
    forColor: 'b',
    family: 'Française',
    eco: 'C00–C19',
    intro: 'Solide mais stratégiquement engagée : les Noirs acceptent un fou c8 momentanément passif en échange d\'une structure de pions très résistante.',
    variations: [
      {
        name: 'Variante d\'Avance',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e6', c: 'Prépare ...d5 en soutenant le pion avant de le pousser.' },
          { s: 'd4', c: '' },
          { s: 'd5', c: 'Défie immédiatement le centre blanc.' },
          { s: 'e5', c: "Avance le pion plutôt que de l'échanger : gagne de l'espace mais fixe la structure." },
          { s: 'c5', c: 'Contre-attaque la base du centre blanc (d4), thème central de la variante.' },
          { s: 'c3', c: 'Soutient d4.' },
          { s: 'Nc6', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Qb6', c: "Met la pression sur d4, coup thématique de l'Avance." },
          { s: 'a3', c: "Prépare b4 pour gagner de l'espace sur l'aile dame." },
          { s: 'Nh6', c: 'Vise à contrôler f5 et rejoindre f5, plan typique du camp noir.' },
        ],
      },
      {
        name: 'Variante d\'Échange',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e6', c: '' },
          { s: 'd4', c: '' },
          { s: 'd5', c: '' },
          { s: 'exd5', c: 'Simplifie la structure : réputée peu ambitieuse mais solide.' },
          { s: 'exd5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Bd3', c: '' },
          { s: 'Bd6', c: 'Développement symétrique et naturel des deux côtés.' },
          { s: 'O-O', c: '' },
          { s: 'O-O', c: 'Position équilibrée où l\'initiative se gagne par de petites finesses de plan.' },
        ],
      },
      {
        name: 'Variante Tarrasch',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e6', c: '' },
          { s: 'd4', c: '' },
          { s: 'd5', c: '' },
          { s: 'Nd2', c: "Évite le clouage ...Bb4 possible après Nc3, au prix d'un développement un peu moins actif." },
          { s: 'Nf6', c: '' },
          { s: 'e5', c: '' },
          { s: 'Nfd7', c: '' },
          { s: 'Bd3', c: '' },
          { s: 'c5', c: 'Contre-attaque classique de la Française contre le centre blanc.' },
          { s: 'c3', c: '' },
          { s: 'Nc6', c: '' },
          { s: 'Ne2', c: "Rejoint f4 ou g3 pour soutenir le centre, plan caractéristique de la Tarrasch." },
        ],
      },
      {
        name: 'Variante Winawer',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e6', c: '' },
          { s: 'd4', c: '' },
          { s: 'd5', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'Bb4', c: 'Cloue le cavalier c3 : la Winawer, la ligne la plus tranchante contre 3.Nc3.' },
          { s: 'e5', c: 'Gagne de l\'espace pendant que le fou noir reste clouant.' },
          { s: 'c5', c: 'Contre-attaque immédiate le centre.' },
          { s: 'a3', c: 'Force la décision du fou.' },
          { s: 'Bxc3+', c: '' },
          { s: 'bxc3', c: 'Les Blancs acceptent des pions doublés pour la paire de fous et l\'espace.' },
          { s: 'Ne7', c: 'Prépare ...Qa5 ou ...Nf5 selon les plans, position très riche et étudiée.' },
        ],
      },
    ],
  },

  {
    id: 'caro-kann',
    forColor: 'b',
    family: 'Caro-Kann',
    eco: 'B10–B19',
    intro: 'Aussi solide que la Française mais sans enfermer le fou c8, qui sort avant ...e6. Réputation de forteresse, prisée par les joueurs positionnels.',
    variations: [
      {
        name: 'Variante Classique',
        moves: [
          { s: 'e4', c: '' },
          { s: 'c6', c: "Prépare ...d5 tout en gardant la case d5 défendue par le pion c, contrairement à la Française." },
          { s: 'd4', c: '' },
          { s: 'd5', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'dxe4', c: '' },
          { s: 'Nxe4', c: '' },
          { s: 'Bf5', c: 'Sort le fou avant ...e6 — l\'avantage clé de la Caro-Kann sur la Française.' },
          { s: 'Ng3', c: 'Chasse le fou en attaquant.' },
          { s: 'Bg6', c: '' },
          { s: 'h4', c: 'Gagne de l\'espace et prépare h5 pour fixer une faiblesse.' },
          { s: 'h6', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nd7', c: 'Position saine et classique, très solide pour les Noirs.' },
          { s: 'h5', c: "Pousse encore le fou, gagnant un maximum d'espace à l'aile roi." },
          { s: 'Bh7', c: 'Le fou reste actif sur cette case, bien protégé.' },
          { s: 'Bd3', c: 'Propose l\'échange pour retirer ce bon fou noir.' },
          { s: 'Bxd3', c: '' },
        ],
      },
      {
        name: 'Variante d\'Avance',
        moves: [
          { s: 'e4', c: '' },
          { s: 'c6', c: '' },
          { s: 'd4', c: '' },
          { s: 'd5', c: '' },
          { s: 'e5', c: 'Gagne de l\'espace, fixe la structure comme dans la Française d\'Avance.' },
          { s: 'Bf5', c: 'Développement immédiat du fou, avant que la position ne se ferme davantage.' },
          { s: 'Nf3', c: '' },
          { s: 'e6', c: '' },
          { s: 'Be2', c: 'Traitement moderne et positionnel (plutôt que Nf3-h4 agressif contre le fou).' },
          { s: 'c5', c: 'Contre-attaque thématique le centre blanc.' },
          { s: 'Be3', c: '' },
          { s: 'Nc6', c: 'Position équilibrée avec plans clairs des deux côtés.' },
        ],
      },
      {
        name: 'Variante d\'Échange',
        moves: [
          { s: 'e4', c: '' },
          { s: 'c6', c: '' },
          { s: 'd4', c: '' },
          { s: 'd5', c: '' },
          { s: 'exd5', c: '' },
          { s: 'cxd5', c: 'Structure symétrique, souvent choisie pour un jeu plus calme et technique.' },
          { s: 'Bd3', c: '' },
          { s: 'Nc6', c: '' },
          { s: 'c3', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Bf4', c: 'Développement naturel, position équilibrée proche de la Française d\'Échange.' },
        ],
      },
    ],
  },

  {
    id: 'scandinavian',
    forColor: 'b',
    family: 'Scandinave',
    eco: 'B01',
    intro: 'Défie e4 immédiatement, quitte à perdre un temps en ramenant la dame — simple à apprendre et pleine de pièges pour l\'adversaire imprudent.',
    variations: [
      {
        name: 'Ligne principale 2...Dxd5',
        moves: [
          { s: 'e4', c: '' },
          { s: 'd5', c: 'Frappe le centre tout de suite.' },
          { s: 'exd5', c: '' },
          { s: 'Qxd5', c: 'Récupère le pion, au prix d\'un temps que les Blancs vont exploiter.' },
          { s: 'Nc3', c: 'Développe en attaquant la dame.' },
          { s: 'Qa5', c: 'Case la plus active, ligne principale moderne.' },
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'c6', c: 'Prépare ...Bf5 ou ...Nbd7, position solide malgré le temps perdu.' },
          { s: 'Bc4', c: '' },
          { s: 'Bf5', c: 'Développement complet, position jouable et bien connue.' },
        ],
      },
      {
        name: 'Ligne moderne 2...Cf6',
        moves: [
          { s: 'e4', c: '' },
          { s: 'd5', c: '' },
          { s: 'exd5', c: '' },
          { s: 'Nf6', c: 'Retarde la reprise de la dame pour éviter de perdre du temps.' },
          { s: 'd4', c: '' },
          { s: 'Nxd5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'g6', c: 'Fianchetto rapide, structure flexible et sûre.' },
          { s: 'Bc4', c: '' },
          { s: 'Nb6', c: 'Chasse le fou avant de développer le reste.' },
          { s: 'Bb3', c: '' },
          { s: 'Bg7', c: 'Position saine, plus facile à jouer que la ligne principale.' },
        ],
      },
    ],
  },

  {
    id: 'pirc-modern',
    forColor: 'b',
    family: 'Pirc / Moderne',
    eco: 'B06–B09',
    intro: 'Les Noirs laissent les Blancs occuper le centre pour mieux le contre-attaquer avec les pièces (fianchetto en g7) plutôt qu\'avec les pions.',
    variations: [
      {
        name: 'Système Classique',
        moves: [
          { s: 'e4', c: '' },
          { s: 'd6', c: 'Prépare ...Nf6 et ...g6 sans s\'engager au centre tout de suite.' },
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'g6', c: 'Fianchetto du fou : il contrôlera la grande diagonale et le centre à distance.' },
          { s: 'Nf3', c: '' },
          { s: 'Bg7', c: '' },
          { s: 'Be2', c: '' },
          { s: 'O-O', c: '' },
          { s: 'O-O', c: '' },
          { s: 'c6', c: 'Prépare ...Qc7 et ...b5, contre-jeu typique sur l\'aile dame.' },
        ],
      },
      {
        name: 'Attaque Autrichienne',
        moves: [
          { s: 'e4', c: '' },
          { s: 'd6', c: '' },
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'g6', c: '' },
          { s: 'f4', c: 'Grand centre de pions et attaque immédiate : la ligne la plus agressive contre la Pirc.' },
          { s: 'Bg7', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'O-O', c: '' },
          { s: 'Bd3', c: '' },
          { s: 'c5', c: 'Contre-attaque immédiate avant que les Blancs ne consolident e4-d4-f4.' },
        ],
      },
    ],
  },

  {
    id: 'alekhine',
    forColor: 'b',
    family: 'Alekhine',
    eco: 'B02–B05',
    intro: 'Provoque volontairement l\'avance des pions blancs pour les attaquer ensuite avec les pièces — un pari hypermoderne assumé dès le premier coup.',
    variations: [
      {
        name: 'Variante Moderne',
        moves: [
          { s: 'e4', c: '' },
          { s: 'Nf6', c: 'Attaque e4 immédiatement, invitant les Blancs à avancer leurs pions centraux.' },
          { s: 'e5', c: 'Chasse le cavalier en gagnant de l\'espace — exactement ce que les Noirs espéraient provoquer.' },
          { s: 'Nd5', c: '' },
          { s: 'd4', c: '' },
          { s: 'd6', c: 'Contre-attaque immédiatement la chaîne de pions blancs.' },
          { s: 'Nf3', c: '' },
          { s: 'Bg4', c: 'Développement actif, met en cause le contrôle du centre.' },
          { s: 'Be2', c: '' },
          { s: 'e6', c: '' },
          { s: 'O-O', c: '' },
          { s: 'Be7', c: 'Position dynamique où le centre blanc, bien qu\'imposant, peut devenir une cible.' },
        ],
      },
      {
        name: 'Attaque des Quatre Pions',
        moves: [
          { s: 'e4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'e5', c: '' },
          { s: 'Nd5', c: '' },
          { s: 'd4', c: '' },
          { s: 'd6', c: '' },
          { s: 'c4', c: 'Pousse un troisième pion central, cherchant à écraser les Noirs par l\'espace.' },
          { s: 'Nb6', c: '' },
          { s: 'f4', c: 'Le quatrième pion : position maximaliste, à double tranchant.' },
          { s: 'dxe5', c: 'Ouvre le jeu avant que les Blancs ne consolident cet énorme centre.' },
          { s: 'fxe5', c: '' },
          { s: 'Nc6', c: 'Attaque immédiatement e5, la cible thématique de toute la ligne.' },
        ],
      },
    ],
  },

  {
    id: 'kings-gambit',
    forColor: 'w',
    family: 'Gambit du Roi',
    eco: 'C30–C39',
    intro: 'Sacrifie un pion dès le second coup pour ouvrir la colonne f et attaquer directement — romantique, rare aujourd\'hui, redoutable si l\'adversaire ne connaît pas la théorie.',
    variations: [
      {
        name: 'Accepté, ligne classique',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e5', c: '' },
          { s: 'f4', c: 'Offre le pion pour ouvrir la colonne f et prendre le centre avec d4 ensuite.' },
          { s: 'exf4', c: 'Accepte le gambit.' },
          { s: 'Nf3', c: 'Empêche ...Qh4+ et prépare de reprendre le pion.' },
          { s: 'g5', c: 'Défend le pion f4 en gagnant de l\'espace, ligne principale historique.' },
          { s: 'h4', c: 'Attaque immédiatement la chaîne g5-f4.' },
          { s: 'g4', c: '' },
          { s: 'Ne5', c: "Le cavalier trouve un poste avancé et vise f7/g4, position très tranchante." },
        ],
      },
      {
        name: 'Refusé : Contre-Gambit Falkbeer',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e5', c: '' },
          { s: 'f4', c: '' },
          { s: 'd5', c: 'Refuse le pion et contre-attaque immédiatement au centre.' },
          { s: 'exd5', c: '' },
          { s: 'e4', c: 'Gagne de l\'espace et de l\'initiative, compensant largement le pion sacrifié.' },
          { s: 'd3', c: 'Cherche à ouvrir le jeu avant que les Noirs ne consolident.' },
          { s: 'Nf6', c: '' },
          { s: 'dxe4', c: '' },
          { s: 'Nxe4', c: 'Les Noirs ont un développement rapide et une forte initiative pour le pion.' },
        ],
      },
    ],
  },

  {
    id: 'vienna',
    forColor: 'w',
    family: 'Partie Viennoise',
    eco: 'C25–C29',
    intro: 'Développe le cavalier avant le fou pour garder plus d\'options, y compris un gambit f4 retardé.',
    variations: [
      {
        name: 'Gambit Viennois',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e5', c: '' },
          { s: 'Nc3', c: 'Développe en gardant l\'option f4 pour plus tard.' },
          { s: 'Nf6', c: '' },
          { s: 'f4', c: 'Gambit retardé, même idée que le Gambit du Roi mais avec le cavalier déjà développé.' },
          { s: 'exf4', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'g5', c: '' },
          { s: 'h4', c: '' },
          { s: 'g4', c: '' },
          { s: 'Ng5', c: 'Position tranchante proche du Gambit du Roi, avec un cavalier de plus en jeu.' },
        ],
      },
      {
        name: 'Variante Tranquille',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e5', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'Nc6', c: '' },
          { s: 'Bc4', c: 'Transpose vers des structures proches de l\'Italienne.' },
          { s: 'Bc5', c: '' },
          { s: 'd3', c: '' },
          { s: 'd6', c: '' },
          { s: 'f4', c: 'Toujours l\'option d\'attaque, ici avec plus de préparation.' },
          { s: 'Nf6', c: 'Position équilibrée, riche en plans stratégiques.' },
        ],
      },
    ],
  },

  {
    id: 'petrov',
    forColor: 'b',
    family: 'Défense Russe (Petrov)',
    eco: 'C42–C43',
    intro: 'Répond à l\'attaque de e5 par une contre-attaque symétrique sur e4 plutôt que par une défense passive — réputation de forteresse au plus haut niveau.',
    variations: [
      {
        name: 'Ligne Classique',
        moves: [
          { s: 'e4', c: '' },
          { s: 'e5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nf6', c: 'Contre-attaque e4 au lieu de défendre e5 — symétrie immédiate.' },
          { s: 'Nxe5', c: 'Prend le pion, comptant sur le fait que ...Nxe4 est aussi possible pour les deux camps.' },
          { s: 'd6', c: 'Chasse le cavalier avant de reprendre l\'égalité matérielle.' },
          { s: 'Nf3', c: '' },
          { s: 'Nxe4', c: 'Récupère le pion, position parfaitement symétrique en matériel.' },
          { s: 'd4', c: '' },
          { s: 'd5', c: '' },
          { s: 'Bd3', c: '' },
          { s: 'Nc6', c: 'Position solide et bien équilibrée, très étudiée au plus haut niveau.' },
        ],
      },
    ],
  },

  // ---------------------------------------------------------------- 1.d4 openings
  {
    id: 'queens-gambit',
    forColor: 'w',
    family: 'Gambit Dame',
    eco: 'D06–D69',
    intro: 'Offre un pion périphérique (c4) pour attirer le pion d5 loin du centre et prendre le contrôle des cases centrales — rarement un vrai sacrifice, presque toujours repris.',
    variations: [
      {
        name: 'Accepté (QGA)',
        moves: [
          { s: 'd4', c: '' },
          { s: 'd5', c: '' },
          { s: 'c4', c: 'Attaque d5 depuis le flanc : si les Noirs prennent, les Blancs regagnent le temps avec e4 ou Nf3 puis Bxc4.' },
          { s: 'dxc4', c: 'Accepte le pion, temporairement.' },
          { s: 'Nf3', c: 'Développe avant de reprendre le pion, plus flexible que e4 immédiat.' },
          { s: 'Nf6', c: '' },
          { s: 'e3', c: '' },
          { s: 'e6', c: '' },
          { s: 'Bxc4', c: 'Reprend le pion : les Blancs ont un développement plus rapide en échange.' },
          { s: 'c5', c: 'Contre-attaque le centre avant que les Blancs ne consolident.' },
          { s: 'O-O', c: '' },
          { s: 'a6', c: 'Position équilibrée, très jouée depuis plus d\'un siècle.' },
        ],
      },
      {
        name: 'Refusé, Défense Orthodoxe',
        moves: [
          { s: 'd4', c: '' },
          { s: 'd5', c: '' },
          { s: 'c4', c: '' },
          { s: 'e6', c: 'Refuse le pion, soutient d5 solidement — au prix d\'enfermer temporairement le fou c8.' },
          { s: 'Nc3', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Bg5', c: 'Cloue le cavalier, augmentant la pression sur d5.' },
          { s: 'Be7', c: '' },
          { s: 'e3', c: '' },
          { s: 'O-O', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'h6', c: 'Pose la question au fou avant de continuer le développement.' },
          { s: 'Bh4', c: 'Position classique de la Défense Orthodoxe, jouée par tous les champions du monde.' },
        ],
      },
      {
        name: 'Défense Slave',
        moves: [
          { s: 'd4', c: '' },
          { s: 'd5', c: '' },
          { s: 'c4', c: '' },
          { s: 'c6', c: 'Soutient d5 sans enfermer le fou c8, qui pourra sortir en f5 ou g4.' },
          { s: 'Nf3', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'dxc4', c: 'Prend le pion maintenant que le fou c8 est encore libre.' },
          { s: 'a4', c: 'Empêche ...b5 qui défendrait le pion c4 supplémentaire.' },
          { s: 'Bf5', c: 'Développement actif du fou avant ...e6, avantage clé de la Slave sur l\'Orthodoxe.' },
          { s: 'e3', c: '' },
          { s: 'e6', c: 'Position solide et flexible, l\'une des défenses les plus fiables contre 1.d4.' },
        ],
      },
      {
        name: 'Défense Tarrasch',
        moves: [
          { s: 'd4', c: '' },
          { s: 'd5', c: '' },
          { s: 'c4', c: '' },
          { s: 'e6', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'c5', c: "Contre-attaque immédiatement d4 plutôt que de défendre passivement — accepte un pion isolé potentiel." },
          { s: 'cxd5', c: '' },
          { s: 'exd5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nc6', c: '' },
          { s: 'g3', c: 'Fianchetto pour surveiller d5 à distance, plan classique contre la Tarrasch.' },
          { s: 'Nf6', c: 'Position dynamique où l\'activité des pièces noires compense le pion isolé.' },
        ],
      },
    ],
  },

  {
    id: 'kings-indian',
    forColor: 'b',
    family: 'Est-Indienne (King\'s Indian)',
    eco: 'E60–E99',
    intro: 'Les Noirs laissent volontairement les Blancs occuper tout le centre pour le frapper ensuite par ...e5 ou ...c5 — une contre-attaque hypermoderne très populaire pour jouer pour le gain.',
    variations: [
      {
        name: 'Variante Classique',
        moves: [
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'c4', c: '' },
          { s: 'g6', c: 'Fianchetto immédiat : le fou g7 surveillera tout le centre à distance.' },
          { s: 'Nc3', c: '' },
          { s: 'Bg7', c: '' },
          { s: 'e4', c: 'Les Blancs prennent tout l\'espace central, exactement ce que les Noirs autorisent.' },
          { s: 'd6', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'O-O', c: '' },
          { s: 'Be2', c: '' },
          { s: 'e5', c: 'Le coup thématique : frappe le centre blanc au moment choisi par les Noirs.' },
          { s: 'O-O', c: '' },
          { s: 'Nc6', c: 'Position dynamique, riche en plans d\'attaque de pions sur les deux ailes.' },
        ],
      },
      {
        name: 'Attaque Sämisch',
        moves: [
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'c4', c: '' },
          { s: 'g6', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'Bg7', c: '' },
          { s: 'e4', c: 'Prend tout le centre avant de préparer f3-Be3-Qd2 pour roquer long et attaquer.' },
          { s: 'd6', c: '' },
          { s: 'f3', c: 'Soutient e4 solidement, coup signature de la Sämisch.' },
          { s: 'O-O', c: '' },
          { s: 'Be3', c: '' },
          { s: 'e5', c: '' },
          { s: 'Nge2', c: 'Le pion e4 libère cette case : le cavalier reste flexible plutôt que de bloquer f3.' },
          { s: 'Nc6', c: 'Position très tranchante avec roques souvent opposés.' },
        ],
      },
    ],
  },

  {
    id: 'grunfeld',
    forColor: 'b',
    family: 'Grünfeld',
    eco: 'D70–D99',
    intro: 'Les Noirs cèdent le centre puis le frappent immédiatement avec ...c5, transformant les pions centraux blancs en cible plutôt qu\'en force.',
    variations: [
      {
        name: 'Variante d\'Échange',
        moves: [
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'c4', c: '' },
          { s: 'g6', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'd5', c: 'Frappe c4 immédiatement, à la différence de l\'Est-Indienne qui joue ...d6.' },
          { s: 'cxd5', c: '' },
          { s: 'Nxd5', c: '' },
          { s: 'e4', c: 'Grand centre de pions, chasse le cavalier.' },
          { s: 'Nxc3', c: '' },
          { s: 'bxc3', c: 'Les Blancs ont un centre imposant mais des pions doublés vulnérables.' },
          { s: 'Bg7', c: 'Le fou g7 attaquera ce centre toute la partie — idée maîtresse de la Grünfeld.' },
          { s: 'Bc4', c: '' },
          { s: 'c5', c: 'Frappe immédiatement le centre blanc.' },
        ],
      },
      {
        name: 'Système Russe',
        moves: [
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'c4', c: '' },
          { s: 'g6', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'd5', c: '' },
          { s: 'Nf3', c: 'Développe avant de décider du centre, plus flexible que 4.cxd5.' },
          { s: 'Bg7', c: '' },
          { s: 'Qb3', c: 'Attaque d5 une deuxième fois tout en visant b7.' },
          { s: 'dxc4', c: '' },
          { s: 'Qxc4', c: '' },
          { s: 'O-O', c: 'Position solide, moins tranchante que l\'Échange mais très étudiée.' },
        ],
      },
    ],
  },

  {
    id: 'nimzo-indian',
    forColor: 'b',
    family: 'Nimzo-Indienne',
    eco: 'E20–E59',
    intro: 'Cloue le cavalier c3 dès le troisième coup pour empêcher e4 et contrôler le centre avec les pièces plutôt qu\'avec les pions — l\'une des défenses les plus solides et respectées contre 1.d4.',
    variations: [
      {
        name: 'Variante Classique (Capablanca)',
        moves: [
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'c4', c: '' },
          { s: 'e6', c: 'Prépare ...Bb4 avant de fianchetter, gardant la case d5 flexible.' },
          { s: 'Nc3', c: '' },
          { s: 'Bb4', c: 'Cloue le cavalier : empêche e4 et menace de doubler les pions blancs par ...Bxc3.' },
          { s: 'Qc2', c: 'Évite les pions doublés en préparant de reprendre en c3 avec la dame.' },
          { s: 'O-O', c: '' },
          { s: 'a3', c: 'Force la décision immédiate du fou.' },
          { s: 'Bxc3+', c: '' },
          { s: 'Qxc3', c: 'Les Blancs ont la paire de fous, les Noirs un jeu solide et sans faiblesse.' },
          { s: 'b6', c: 'Fianchetto pour contrôler e4 et compenser la paire de fous adverse.' },
        ],
      },
      {
        name: 'Variante Rubinstein',
        moves: [
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'c4', c: '' },
          { s: 'e6', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'Bb4', c: '' },
          { s: 'e3', c: 'Développement solide et flexible, la ligne la plus jouée au plus haut niveau.' },
          { s: 'O-O', c: '' },
          { s: 'Bd3', c: '' },
          { s: 'd5', c: 'Frappe le centre au moment opportun.' },
          { s: 'Nf3', c: '' },
          { s: 'c5', c: 'Position équilibrée, extrêmement riche en plans stratégiques.' },
        ],
      },
    ],
  },

  {
    id: 'queens-indian',
    forColor: 'b',
    family: 'Est-Indienne Dame (Queen\'s Indian)',
    eco: 'E12–E19',
    intro: 'Fianchetto le fou dame en b7 pour contrôler e4 à distance — un jumeau positionnel de la Nimzo-Indienne, joué quand les Blancs évitent Nc3.',
    variations: [
      {
        name: 'Ligne Principale',
        moves: [
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'c4', c: '' },
          { s: 'e6', c: '' },
          { s: 'Nf3', c: "Évite Nc3, donc ...Bb4 n'est plus clouant : les Noirs choisissent un plan différent." },
          { s: 'b6', c: 'Prépare le fianchetto du fou dame pour contrôler e4 sans cloueur.' },
          { s: 'g3', c: 'Fianchetto miroir des Blancs, très solide.' },
          { s: 'Ba6', c: 'Idée thématique : attaque c4 avant que les Blancs ne le défendent.' },
          { s: 'b3', c: '' },
          { s: 'Bb4+', c: '' },
          { s: 'Bd2', c: '' },
          { s: 'Be7', c: 'Position équilibrée et très solide, réputée difficile à déséquilibrer.' },
        ],
      },
    ],
  },

  {
    id: 'dutch',
    forColor: 'b',
    family: 'Hollandaise',
    eco: 'A80–A99',
    intro: 'Gagne de l\'espace à l\'aile roi dès le premier coup noir, préparant une attaque sur le roque adverse — combative mais affaiblit légèrement la case e6/roi noir.',
    variations: [
      {
        name: 'Système Leningrad',
        moves: [
          { s: 'd4', c: '' },
          { s: 'f5', c: 'Contrôle e4 et prépare une attaque à l\'aile roi, au prix d\'un léger affaiblissement du roi.' },
          { s: 'g3', c: 'Fianchetto pour contester la diagonale a1-h8 que les Noirs vont aussi viser.' },
          { s: 'Nf6', c: '' },
          { s: 'Bg2', c: '' },
          { s: 'g6', c: 'Double fianchetto : le Système Leningrad, le plus agressif des traitements hollandais.' },
          { s: 'Nf3', c: '' },
          { s: 'Bg7', c: '' },
          { s: 'O-O', c: '' },
          { s: 'O-O', c: '' },
          { s: 'c4', c: '' },
          { s: 'd6', c: 'Position dynamique où les Noirs jouent pour ...e5 avec du contre-jeu actif.' },
        ],
      },
      {
        name: 'Stonewall',
        moves: [
          { s: 'd4', c: '' },
          { s: 'f5', c: '' },
          { s: 'c4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'g3', c: '' },
          { s: 'e6', c: '' },
          { s: 'Bg2', c: '' },
          { s: 'd5', c: "Le \"mur de pierre\" : chaîne de pions d5-e6-f5 très solide mais qui enferme le fou c8." },
          { s: 'Nf3', c: '' },
          { s: 'Bd6', c: 'Le fou f8 compense en visant directement h2, plan d\'attaque classique du Stonewall.' },
          { s: 'O-O', c: '' },
          { s: 'O-O', c: 'Position à plans clairs : attaque à l\'aile roi pour les Noirs, jeu sur les cases noires pour les Blancs.' },
        ],
      },
    ],
  },

  {
    id: 'benoni',
    forColor: 'b',
    family: 'Benoni Moderne',
    eco: 'A56–A79',
    intro: 'Après 1.d4 Nf6 2.c4 c5, les Noirs acceptent une structure de pions asymétrique (pion d5 blanc contre majorité noire à l\'aile dame) pour un jeu très combatif.',
    variations: [
      {
        name: 'Ligne Principale',
        moves: [
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'c4', c: '' },
          { s: 'c5', c: 'Défie immédiatement le centre par le flanc.' },
          { s: 'd5', c: 'Avance plutôt que d\'échanger, gagnant de l\'espace et fixant la structure Benoni.' },
          { s: 'e6', c: 'Frappe le pion d5 pour l\'échanger contre le pion e.' },
          { s: 'Nc3', c: '' },
          { s: 'exd5', c: '' },
          { s: 'cxd5', c: '' },
          { s: 'd6', c: '' },
          { s: 'e4', c: '' },
          { s: 'g6', c: 'Fianchetto classique : les Noirs visent une contre-attaque par ...b5 et pression sur e4.' },
        ],
      },
    ],
  },

  {
    id: 'benko',
    forColor: 'b',
    family: 'Gambit Benko',
    eco: 'A57–A59',
    intro: 'Sacrifie un pion à l\'aile dame pour ouvrir les colonnes a et b contre le roi blanc — compensation durable et faciles à jouer pour les Noirs.',
    variations: [
      {
        name: 'Ligne Acceptée',
        moves: [
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'c4', c: '' },
          { s: 'c5', c: '' },
          { s: 'd5', c: '' },
          { s: 'b5', c: 'Le gambit : sacrifie ce pion pour ouvrir les colonnes a et b contre le roque blanc.' },
          { s: 'cxb5', c: 'Accepte le sacrifice.' },
          { s: 'a6', c: 'Ouvre une deuxième fois pour accélérer l\'ouverture des colonnes.' },
          { s: 'bxa6', c: '' },
          { s: 'Bxa6', c: 'Les Noirs ont un pion de moins mais une pression durable et facile à jouer sur l\'aile dame.' },
          { s: 'Nc3', c: '' },
          { s: 'd6', c: 'Développement classique, préparant ...g6 et ...Bg7.' },
        ],
      },
    ],
  },

  {
    id: 'london',
    forColor: 'w',
    family: 'Système Londres',
    eco: 'D02',
    intro: 'Système universel pour les Blancs : même schéma de développement (Bf4, e3, Nf3, Bd3, O-O) contre presque toute réponse noire — peu théorique, très populaire aux niveaux amateur et pro.',
    variations: [
      {
        name: 'Ligne Principale',
        moves: [
          { s: 'd4', c: '' },
          { s: 'd5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Bf4', c: "Sort le fou avant e3, pour ne pas l'enfermer — l'idée signature du Système Londres." },
          { s: 'e6', c: '' },
          { s: 'e3', c: '' },
          { s: 'Bd6', c: 'Défie directement le fou blanc.' },
          { s: 'Bg3', c: 'Évite l\'échange en gardant la diagonale.' },
          { s: 'O-O', c: '' },
          { s: 'Bd3', c: '' },
          { s: 'c5', c: 'Position solide et facile à comprendre pour les deux camps, même schéma quel que soit l\'adversaire.' },
        ],
      },
    ],
  },

  {
    id: 'trompowsky',
    forColor: 'w',
    family: 'Trompowsky',
    eco: 'A45',
    intro: 'Cloue immédiatement le cavalier f6 avant que les Noirs n\'aient pu se préparer — évite toute la théorie des défenses indiennes classiques.',
    variations: [
      {
        name: 'Ligne Principale',
        moves: [
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Bg5', c: "Cloue le cavalier immédiatement, sortant des sentiers battus de 2.c4." },
          { s: 'e6', c: '' },
          { s: 'e4', c: 'Grand centre de pions, profitant du fou déjà développé.' },
          { s: 'h6', c: '' },
          { s: 'Bxf6', c: '' },
          { s: 'Qxf6', c: 'Les Blancs cèdent la paire de fous mais gagnent de l\'espace et un développement rapide.' },
          { s: 'Nc3', c: '' },
          { s: 'd6', c: '' },
          { s: 'Qd2', c: 'Prépare O-O-O, position agressive et peu théorique.' },
        ],
      },
    ],
  },

  {
    id: 'colle',
    forColor: 'w',
    family: 'Système Colle',
    eco: 'D05',
    intro: 'Système tranquille pour les Blancs (Nf3, e3, Bd3, c3) qui prépare une poussée e4 explosive une fois les pièces développées — simple à apprendre, redoutable si sous-estimé.',
    variations: [
      {
        name: 'Ligne Principale',
        moves: [
          { s: 'd4', c: '' },
          { s: 'd5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'e3', c: 'Développement modeste mais flexible, prépare Bd3 et c3.' },
          { s: 'e6', c: '' },
          { s: 'Bd3', c: 'Vise h7, idée clé du système derrière une préparation patiente.' },
          { s: 'c5', c: '' },
          { s: 'c3', c: 'Soutient d4 avant la poussée thématique e4.' },
          { s: 'Nc6', c: '' },
          { s: 'Nbd2', c: '' },
          { s: 'Bd6', c: 'Les Blancs préparent e4 : si les Noirs ne réagissent pas, le centre s\'ouvre en leur faveur.' },
        ],
      },
    ],
  },

  {
    id: 'catalan',
    forColor: 'w',
    family: 'Catalane',
    eco: 'E00–E09',
    intro: 'Combine les idées du Gambit Dame et d\'un fianchetto en g2 : pression durable sur d5/c4 et la grande diagonale, très prisée au niveau mondial pour son faible risque.',
    variations: [
      {
        name: 'Catalane Ouverte',
        moves: [
          { s: 'd4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'c4', c: '' },
          { s: 'e6', c: '' },
          { s: 'g3', c: 'Fianchetto qui vise d5 et c4 en même temps, sur la grande diagonale.' },
          { s: 'd5', c: '' },
          { s: 'Bg2', c: '' },
          { s: 'Be7', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'O-O', c: '' },
          { s: 'O-O', c: '' },
          { s: 'dxc4', c: 'Catalane Ouverte : les Noirs prennent le pion, pariant sur leur solidité contre la pression durable du fou g2.' },
        ],
      },
    ],
  },

  // ---------------------------------------------------------------- Flank openings
  {
    id: 'english',
    forColor: 'w',
    family: 'Anglaise',
    eco: 'A10–A39',
    intro: 'Débute par le flanc (1.c4) pour garder un maximum de flexibilité : peut transposer vers le Gambit Dame, une Sicilienne inversée ou un jeu indépendant.',
    variations: [
      {
        name: 'Symétrique',
        moves: [
          { s: 'c4', c: 'Contrôle d5 depuis le flanc, garde toutes les options de structure ouvertes.' },
          { s: 'c5', c: 'Réponse miroir : symétrie complète au départ.' },
          { s: 'Nc3', c: '' },
          { s: 'Nc6', c: '' },
          { s: 'g3', c: 'Fianchetto classique pour contrôler d5 à distance.' },
          { s: 'g6', c: '' },
          { s: 'Bg2', c: '' },
          { s: 'Bg7', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nf6', c: 'Symétrie parfaite : la partie se décide sur qui rompt l\'équilibre en premier.' },
        ],
      },
      {
        name: 'Sicilienne Inversée',
        moves: [
          { s: 'c4', c: '' },
          { s: 'e5', c: 'Occupe le centre directement : une Sicilienne avec une couleur en plus pour les Blancs.' },
          { s: 'Nc3', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nc6', c: '' },
          { s: 'g3', c: '' },
          { s: 'd5', c: 'Prend le centre pendant que les Blancs finissent leur fianchetto.' },
          { s: 'cxd5', c: '' },
          { s: 'Nxd5', c: '' },
          { s: 'Bg2', c: '' },
          { s: 'Nb6', c: 'Position dynamique où le temps de plus des Blancs (dû à l\'inversion) compte vraiment.' },
        ],
      },
      {
        name: 'Contre 1...Cf6',
        moves: [
          { s: 'c4', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Nc3', c: '' },
          { s: 'e6', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'd5', c: 'Reprend le centre au moment opportun, position proche d\'un Gambit Dame refusé.' },
          { s: 'd4', c: 'Transpose directement vers les structures du Gambit Dame.' },
          { s: 'Be7', c: '' },
          { s: 'Bg5', c: '' },
          { s: 'O-O', c: 'Illustre la grande flexibilité de l\'Anglaise : transposition fluide vers d\'autres ouvertures connues.' },
        ],
      },
    ],
  },

  {
    id: 'reti',
    forColor: 'w',
    family: 'Réti',
    eco: 'A04–A09',
    intro: 'Développe le cavalier avant tout engagement de pion central, gardant la possibilité de jouer d4, c4 ou g3 selon la réponse noire.',
    variations: [
      {
        name: 'Contre 1...d5',
        moves: [
          { s: 'Nf3', c: 'Contrôle e5 et d4 sans encore s\'engager sur la structure de pions.' },
          { s: 'd5', c: '' },
          { s: 'c4', c: 'Attaque d5 depuis le flanc, dans l\'esprit du Gambit Dame mais avec le cavalier déjà développé.' },
          { s: 'e6', c: '' },
          { s: 'g3', c: 'Fianchetto pour surveiller d5 et le centre à distance.' },
          { s: 'Nf6', c: '' },
          { s: 'Bg2', c: '' },
          { s: 'Be7', c: '' },
          { s: 'O-O', c: '' },
          { s: 'O-O', c: 'Position flexible, souvent transpose vers une Catalane ou une Anglaise.' },
        ],
      },
      {
        name: 'Attaque Indienne du Roi (contre 1...Cf6)',
        moves: [
          { s: 'Nf3', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'g3', c: 'Fianchetto immédiat : les Blancs adoptent un plan universel, quel que soit le jeu noir.' },
          { s: 'g6', c: '' },
          { s: 'Bg2', c: '' },
          { s: 'Bg7', c: '' },
          { s: 'O-O', c: '' },
          { s: 'O-O', c: '' },
          { s: 'd3', c: 'Prépare e4 avec un plan simple et solide, jouable contre presque toute réponse noire.' },
          { s: 'd6', c: 'Position à la King\'s Indian Attack : plan facile à retenir, bon pour progresser rapidement.' },
        ],
      },
    ],
  },

  {
    id: 'bird',
    forColor: 'w',
    family: 'Bird',
    eco: 'A02–A03',
    intro: 'Réplique de 1.f4 : gagne de l\'espace à l\'aile roi et peut transposer vers une Hollandaise avec une couleur en plus.',
    variations: [
      {
        name: 'Ligne Principale',
        moves: [
          { s: 'f4', c: 'Contrôle e5 et prépare un fianchetto ou un jeu à l\'aile roi.' },
          { s: 'd5', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'e3', c: '' },
          { s: 'g6', c: '' },
          { s: 'Be2', c: '' },
          { s: 'Bg7', c: '' },
          { s: 'O-O', c: '' },
          { s: 'O-O', c: '' },
          { s: 'd3', c: 'Position tranquille, essentiellement une Hollandaise Leningrad inversée.' },
        ],
      },
    ],
  },

  {
    id: 'larsen',
    forColor: 'w',
    family: 'Larsen (Nimzo-Larsen)',
    eco: 'A01',
    intro: 'Fianchetto immédiat du fou dame pour contrôler e4 dès le premier coup — flexible et peu théorique, rendu célèbre par le grand maître danois Bent Larsen.',
    variations: [
      {
        name: 'Ligne Principale',
        moves: [
          { s: 'b3', c: 'Prépare Bb2 pour contrôler e5 et la grande diagonale, sans engager les pions centraux.' },
          { s: 'e5', c: '' },
          { s: 'Bb2', c: 'Le fou vise directement e5 depuis b2.' },
          { s: 'Nc6', c: '' },
          { s: 'e3', c: '' },
          { s: 'Nf6', c: '' },
          { s: 'Bb5', c: 'Cloue le cavalier à la manière d\'une Espagnole, idée typique de Larsen.' },
          { s: 'Bd6', c: '' },
          { s: 'Nf3', c: '' },
          { s: 'O-O', c: 'Position flexible et peu théorique, bonne surprise pour sortir de la préparation adverse.' },
        ],
      },
    ],
  },
];
